---
spring:
  config:
    activate:
      on-profile: client1
server:
  port: 8991

# Конфигурация для клиента 2 (профиль client2)
---
spring:
  config:
    activate:
      on-profile: client2
server:
  port: 8992